version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  scheduler:
    build:
      context: .
      dockerfile: scheduler.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - api
      - redis

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./ui:/app
    command: ["npm", "run", "dev", "--", "--host"]